### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by ColdSauce**

### CODE REVIEW

**Comment by squiffy** [comment]
doesnt need a license. its too free for that

**Comment by domrc** [comment]
I know that this is a couple months old, but gnu all-permissive license? Don't leave software unlicensed as it defaults to being copyrighted (Berne Convention, source:http://gplv3.fsf.org/wiki/index.php/Copyright_law). A simple two-sentence license should suffice. https://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html

**Comment by gabe-k** [comment]
thanks @domrc i'll have to consult my lawyer first

**Comment by domrc** [comment]
Lol, sorry, been spending to much time at fsf.org and gnu.org

**Pull request closed without merging**
